### PR TITLE
Help

### PR DESCRIPTION
**Pull request by juniorknot**
Please upload files to work https://bible.timelesstruths.org/ please =(

### CODE REVIEW

**Comment by juniorknot** [comment]
Upload folder bible please

**Comment by livelysalt** [comment]
@juniorknot The current version of https://bible.timelesstruths.org/ no longer runs on this code base, sorry.

**Comment by juniorknot** [comment]
> @juniorknot The current version of https://bible.timelesstruths.org/ no longer runs on this code base, sorry.

give link of new code please :(

**Comment by livelysalt** [comment]
It would take a bit of work to modify the code environment to work with a public repository. I don't have much time to invest in this project unless you are serious about contributing. What ideas do you have for improving the site?

**Comment by juniorknot** [comment]
I would like to implement  change versions of Bibles, and languages, I have enough time and source more versions and langs bible versions

**Comment by livelysalt** [comment]
What do you suggest for deploying a development environment? I currently just have a local server for that and then FTP to the production host. That's not convenient for collaboration. The code is mainly PHP, with a little JS on the front end. Ideally, I would prefer refactoring to a JAMstack model, and separate the data from the front end. In that case, Netlify would be a good option for the front end, but it would involve a major rewrite to make that happen.

**Comment by juniorknot** [comment]
> What do you suggest for deploying a development environment? I currently just have a local server for that and then FTP to the production host. That's not convenient for collaboration. The code is mainly PHP, with a little JS on the front end. Ideally, I would prefer refactoring to a JAMstack model, and separate the data from the front end. In that case, Netlify would be a good option for the front end, but it would involve a major rewrite to make that happen.

JAM Stack it sounds good, if you can then and it is not too much trouble, can you share the project via zip? my email is vetantra@gmail.com I can work locally

**Comment by livelysalt** [comment]
Sorry about the wait. Due to GMail security, I couldn't send the project as a zip, so I just uploaded the directory to the main repository (see /v4), along with db.zip, which contains the database tables for bible.timelesstruths.org.

**Comment by juniorknot** [comment]
Hello, God bless you, I hope you are well, is it possible for you to upload the following files to the repository?

_config.www.php
_config.admin.php
_config.dev.php

**Comment by livelysalt** [comment]
Those files contain the credentials needed for each environment, such as:
```
<?php // _config.admin.php

$config_db = array(
    'host' => '',
    'user' => '',
    'pass' => '',
    'data' => '',
);

$config_ssh = array(
    'host' => '',
    'port' => 22,
    'user' => '',
    'pass' => '',
);

$config_key = '';
```

**Pull request merged**
